version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: change-detection
      hostname: changedetection
      volumes:
        - /data/misc/changedetection:/datastore
      restart: unless-stopped
