# NodeJS Discord Bot
version: '3.8'
services:
  discord-bot:
    container_name: discord-bot
    image: docker.io/node:18.18-bullseye
    volumes:
      - "/data/bot/discord-bot:/bot" # path to discord bot files
    command: ["node", "."]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "node -v"]
      interval: 30s
      timeout: 10s
      retries: 3
    working_dir: /bot
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true
