version: '3.3'
services:
    adguard:
        image: adguard/adguardhome
        container_name: adguard
        restart: unless-stopped
        volumes:
            - '/data/misc/adguard/data:/opt/adguardhome/work'
            - '/data/misc/adguard/data/conf:/opt/adguardhome/conf'
        ports:
            - '!!SERVER_IP!!:53:53/udp'
        networks:
            - reverseproxy
            - vpn

networks:
  reverseproxy:
    external: true
  vpn:
    external: true
