version: '3'

services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Europe/Prague
    #ports:
        #- "8000:8000" # HTTP
        #- "8443:8443" # HTTPS
        #- "8123:8123" # DYNMAP
        #- "19132:19132/udp" # BEDROCK
        #- "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /data/misc/crafty/backups:/crafty/backups
        - /data/misc/crafty/logs:/crafty/logs
        - /data/misc/crafty/servers:/crafty/servers
        - /data/misc/crafty/config:/crafty/app/config
        - /data/misc/crafty/import:/crafty/import
